version: '2'

services:
  postgres:
    image: 'postgres:9.5.18'
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: 'postgres'

  website:
    depends_on:
      - 'postgres'
    build: .
    command: bash start
    ports:
      - '3000:3000'
    volumes:
      - '.:/easy-food'
    volumes_from:
      - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
  postgres:
  box: